/*
 * sp11-bt-set-addr.c - set the Surface Pro 11 Bluetooth public address.
 *
 * This helper exists for the Qualcomm WCN7850 / FastConnect 7800 Bluetooth
 * controller used in the Surface Pro 11 bring-up flow. On affected installs,
 * Linux may enumerate the controller with a placeholder-like public address
 * such as 00:00:00:00:*; BlueZ then has no usable default controller until the
 * real Bluetooth address, sourced from Windows or another trusted source, is
 * written through the kernel Bluetooth management interface.
 *
 * The older shell helper used btmgmt. That works from an interactive terminal
 * after boot, but testing showed btmgmt can hang in uninterruptible D-state
 * when launched from a cold-boot systemd unit. This program deliberately avoids
 * btmgmt, BlueZ libraries, readline, stdin handling, and any other interactive
 * plumbing. It opens a raw AF_BLUETOOTH / BTPROTO_HCI socket, binds the kernel
 * HCI management control channel, and sends MGMT_OP_SET_PUBLIC_ADDRESS
 * directly.
 *
 * Intended invocation:
 *
 *     sp11-bt-set-addr HCI_INDEX MAC
 *
 * Example with a non-real documentation address:
 *
 *     sp11-bt-set-addr 0 02:11:22:33:44:55
 *
 * In production, the MAC argument must be the device's real Bluetooth address.
 * Do not hard-code, log publicly, commit, or publish a real device address.
 * The repository documentation uses placeholder or locally administered example
 * addresses only.
 *
 * Systemd timing matters. The service generated by scripts/sp11-bluetooth-mac.sh
 * runs this helper Before=bluetooth.service, while the controller is still in
 * its initial DOWN RAW state and before bluetoothd has claimed or powered it.
 * At that point the kernel accepts MGMT_OP_SET_PUBLIC_ADDRESS directly; no
 * power-off sequence, rfkill unblock, bluetoothd restart, or firmware settle
 * sleep is required outside this program.
 *
 * Runtime behavior:
 *
 * - Wait up to 120 seconds for /sys/class/bluetooth/hciN to appear.
 * - Open a fresh raw HCI management socket for each attempt.
 * - Bind HCI_CHANNEL_CONTROL with HCI_DEV_NONE, matching btmgmt's management
 *   channel behavior without using btmgmt itself.
 * - Send MGMT_OP_SET_PUBLIC_ADDRESS (0x0039) to the requested controller index.
 * - Accept either MGMT_EV_CMD_COMPLETE or MGMT_EV_CMD_STATUS for that opcode.
 * - Use a 5 second SO_RCVTIMEO so reads remain bounded.
 * - Retry up to 60 times, reopening the socket between attempts, because early
 *   cold-boot writes can transiently return short writes while HCI management is
 *   still initializing.
 *
 * Exit codes:
 *
 * - 0: address was accepted by the kernel management interface.
 * - 1: controller did not appear, socket/mgmt retries were exhausted, or the
 *      kernel returned a non-success management status.
 * - 2: command-line usage, HCI index, or MAC address validation failed.
 *
 * The helper stores no state and does not read /etc/default directly. The shell
 * installer remains responsible for writing and protecting the local config,
 * then passing SP11_BLUETOOTH_MAC to this binary from the generated unit.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <sys/time.h>
#include <stdint.h>
#include <endian.h>
#include <ctype.h>

#ifndef AF_BLUETOOTH
#define AF_BLUETOOTH   31
#endif
#ifndef BTPROTO_HCI
#define BTPROTO_HCI     1
#endif

#define HCI_CHANNEL_CONTROL      3
#define HCI_DEV_NONE             0xFFFF
#define MGMT_EV_CMD_COMPLETE     0x0001
#define MGMT_EV_CMD_STATUS       0x0002
#define MGMT_OP_SET_PUBLIC_ADDR  0x0039
#define MGMT_STATUS_SUCCESS      0x00

struct sockaddr_hci {
	sa_family_t    hci_family;
	unsigned short hci_dev;
	unsigned short hci_channel;
};

struct mgmt_hdr {
	uint16_t opcode;
	uint16_t index;
	uint16_t len;
} __attribute__((packed));

struct mgmt_ev_cmd_complete {
	uint16_t opcode;
	uint8_t  status;
	uint8_t  data[];
} __attribute__((packed));

struct mgmt_ev_cmd_status {
	uint8_t  status;
	uint16_t opcode;
} __attribute__((packed));

static const char *st_name(uint8_t s)
{
	switch (s) {
	case 0x00: return "success";
	case 0x0a: return "RFKILLED";
	case 0x0b: return "rejected";
	case 0x0d: return "invalid params";
	case 0x14: return "permission denied";
	default:   return "unknown";
	}
}

static int parse_mac(const char *str, uint8_t *out)
{
	const char *p = str;
	int sep = 0;
	for (int i = 0; i < 6; i++) {
		if (!isxdigit((unsigned char)p[0]) || !isxdigit((unsigned char)p[1]))
			return -1;
		char hex[3] = { p[0], p[1], '\0' };
		char *end;
		unsigned long val = strtoul(hex, &end, 16);
		if (*end || val > 0xFF) return -1;
		out[i] = (uint8_t)val;
		p += 2;
		if (i < 5) {
			if (i == 0) sep = (*p == ':') ? 1 : ((*p == '-') ? 2 : 0);
			if ((sep == 1 && *p != ':') || (sep == 2 && *p != '-') || sep == 0)
				return -1;
			p++;
		}
	}
	return (*p == '\0') ? 0 : -1;
}

static int parse_hci(const char *str, uint16_t *out)
{
	char *end;
	unsigned long val = strtoul(str, &end, 10);
	if (*end || val > 65535) return -1;
	*out = (uint16_t)val;
	return 0;
}

static void wait_hci(uint16_t idx)
{
	char path[64];
	snprintf(path, sizeof(path), "/sys/class/bluetooth/hci%u", idx);
	for (int i = 0; i < 120; i++) {
		if (access(path, F_OK) == 0) {
			printf("hci%u ready at T+%ds\n", idx, i + 1);
			return;
		}
		sleep(1);
	}
	fprintf(stderr, "hci%u not found after 120s\n", idx);
	exit(1);
}

static int set_addr_once(int fd, uint16_t idx, const uint8_t *mac)
{
	uint8_t buf[sizeof(struct mgmt_hdr) + 6];
	struct mgmt_hdr *h = (struct mgmt_hdr *)buf;
	h->opcode = htole16(MGMT_OP_SET_PUBLIC_ADDR);
	h->index  = htole16(idx);
	h->len    = htole16(6);
	memcpy(buf + sizeof(*h), mac, 6);

	ssize_t sent = write(fd, buf, sizeof(buf));
	if (sent < 0) {
		fprintf(stderr, "mgmt write failed: %s\n", strerror(errno));
		return -1;
	}
	if ((size_t)sent != sizeof(buf)) {
		fprintf(stderr, "short write %zd/%zu\n", sent, sizeof(buf));
		return -1;
	}

	uint8_t rbuf[2048];
	for (;;) {
		ssize_t n = read(fd, rbuf, sizeof(rbuf));
		if (n < 0) {
			fprintf(stderr, "mgmt read failed: %s\n", strerror(errno));
			return -1;
		}
		if (n < (ssize_t)sizeof(struct mgmt_hdr)) continue;
		struct mgmt_hdr *ev = (struct mgmt_hdr *)rbuf;
		uint16_t code = le16toh(ev->opcode);
		uint16_t ei   = le16toh(ev->index);
		uint16_t elen = le16toh(ev->len);
		if (ei != idx) continue;
		if ((size_t)n < sizeof(*ev) + elen) continue;
		uint8_t st;
		if (code == MGMT_EV_CMD_COMPLETE) {
			if (elen < sizeof(struct mgmt_ev_cmd_complete)) continue;
			struct mgmt_ev_cmd_complete *cc =
				(struct mgmt_ev_cmd_complete *)(rbuf + sizeof(*ev));
			if (le16toh(cc->opcode) != MGMT_OP_SET_PUBLIC_ADDR) continue;
			st = cc->status;
		} else if (code == MGMT_EV_CMD_STATUS) {
			if (elen < sizeof(struct mgmt_ev_cmd_status)) continue;
			struct mgmt_ev_cmd_status *cs =
				(struct mgmt_ev_cmd_status *)(rbuf + sizeof(*ev));
			if (le16toh(cs->opcode) != MGMT_OP_SET_PUBLIC_ADDR) continue;
			st = cs->status;
		} else {
			continue;
		}
		printf("set-public-address  status 0x%02x (%s)\n", st, st_name(st));
		return (st == MGMT_STATUS_SUCCESS) ? 0 : 1;
	}
}

int main(int argc, char **argv)
{
	if (argc != 3) {
		fprintf(stderr, "Usage: %s HCI_INDEX MAC\n", argv[0]);
		return 2;
	}
	uint16_t idx;
	if (parse_hci(argv[1], &idx)) {
		fprintf(stderr, "Bad HCI index: %s\n", argv[1]);
		return 2;
	}
	uint8_t mac[6];
	if (parse_mac(argv[2], mac)) {
		fprintf(stderr, "Bad MAC: %s\n", argv[2]);
		return 2;
	}

	wait_hci(idx);

	struct sockaddr_hci addr = {
		.hci_family = AF_BLUETOOTH,
		.hci_dev = HCI_DEV_NONE,
		.hci_channel = HCI_CHANNEL_CONTROL,
	};

	for (int attempt = 0; attempt < 60; attempt++) {
		if (attempt > 0) sleep(1);

		int fd = socket(AF_BLUETOOTH, SOCK_RAW, BTPROTO_HCI);
		if (fd < 0) {
			if (attempt < 5)
				fprintf(stderr, "socket() failed, retry %d/60\n", attempt + 2);
			continue;
		}

		struct timeval tv = { .tv_sec = 5 };
		setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

		if (bind(fd, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
			close(fd);
			continue;
		}

		int r = set_addr_once(fd, idx, mac);
		close(fd);

		if (r == 0) {
			printf("Success: public address set\n");
			return 0;
		}
		if (r == 1) {
			/* non-success status (e.g. rejected while powered) */
			if (attempt < 59)
				fprintf(stderr, "Retrying (%d/60)...\n", attempt + 2);
			continue;
		}
		/* r == -1: socket failure, retry */
	}

	fprintf(stderr, "Error: failed after 60 attempts\n");
	return 1;
}
